[toolchain]
channel = "nightly-2024-10-18"
components = ["rustfmt", "clippy"]
targets = ["wasm32-wasip1", "wasm32-wasip1-threads", "x86_64-pc-windows-msvc", "aarch64-unknown-linux-gnu"]
profile = "minimal"
