[toolchain]
channel = "nightly-2024-05-03"
components = [ "rustfmt", "rustc-dev", "llvm-tools-preview" ]
targets = [ "wasm32-wasi", "wasm32-wasip1-threads", "x86_64-pc-windows-msvc", "aarch64-unknown-linux-gnu" ]
profile = "minimal"
