[package]
name = "nonlocality_host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1", features = ["rt-multi-thread", "macros", "time", "sync"]}
ratatui = {version = "0", features = []}
crossterm = {version = "0", features = ["event-stream"]}
tokio-stream = "0"
async-stream = "0"
futures = "0"
futures-util = "0"
futures-core = "0"
