[package]
name = "dogbox_blob_layer"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
serde = {version = "1", features = [ "derive" ]}
sha3 = "0"
hex = "0"
async-trait = "0"
tokio = { version = "1", features = ["full"] }
tokio-macros = "2"
