[package]
name = "provide_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
display_bytes = "0.2.1"
nonlocality_env = { path ="../../../nonlocality_env" }
