[package]
name = "hippeus_parser_generator"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
postcard = {version = "1", features = ["use-std"]}
pretty_assertions = "1"

[dev-dependencies]
test-log = {version = "0", features = ["trace", "log", "color"]}
test-case = "3"
