[package]
name = "dogbox_dav_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dogbox_blob_layer = { path ="../dogbox_blob_layer" }
dav-server = "0.5"
hyper = { version = "0.14.0", features = [ "http1", "http2", "server", "stream", "runtime" ] }
tokio = { version = "1.3.0", features = ["full"] }
