# this is for cross compilation to Raspberry Pi (solution found in https://www.reddit.com/r/rust/comments/l82y10/cross_compiling_from_windows_to_linux/)
# [target.aarch64-unknown-linux-gnu]
# linker = "rust-lld"
