[package]
name = "astraea"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
hippeus_parser_generator = { path ="../hippeus_parser_generator" }
tokio = {version = "1", features = ["rt-multi-thread", "macros", "time", "sync"]}
tokio-stream = "0"
async-stream = "0"
futures = "0"
futures-util = "0"
futures-core = "0"
sha3 = "0"
serde = "1"
postcard = {version = "1", features = ["alloc"]}
lazy_static = "1"
rusqlite = {version = "0", features = ["bundled-sqlcipher-vendored-openssl"]}
tempfile = "3"
