[package]
name = "management_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relative-path = "1.9.2"
wasmtime = "20.0.0"
wasi-common = "20.0.0"
normalize-path = "0.2.1"
display_bytes = "0.2.1"
wiggle = "20.0.0"
promising-future = "0.2.4"
os_pipe = "1.1.5"
wasmtime-wasi-threads = "20.0.0"
anyhow = { version = "1.0", default-features = false }
management_interface = { path ="../management_interface" }
essrpc = {version = "0.4.1", features = ["bincode_transport", "async_client"]}
tokio = {version = "1.37.0", features = ["rt-multi-thread", "macros", "net"]}
tokio-util = {version = "0.7.10", features = ["io-util", "io"]}
