[package]
name = "management_interface"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
essrpc = {version = "0.4.1", features = [ ]}
serde = "1.0"
dogbox_blob_layer = { path ="../dogbox/dogbox_blob_layer" }
