name: Rust2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  # https://github.com/mozilla/sccache/blob/main/docs/GHA.md
  SCCACHE_GHA_ENABLED: on
  RUST_BACKTRACE: 1

jobs:
  build:
    name: Rust3
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    concurrency:
      # Group by branch
      group: ${{ github.ref }}
      # Cancel any in-progress jobs in this group to avoid wasting time on obsolete commits
      cancel-in-progress: true

    env:
      SCCACHE_VERSION: "v0.10.0"
      SCCACHE_FILENAME: "sccache-v0.10.0-x86_64-unknown-linux-musl.tar.gz"

    steps:
    - uses: actions/checkout@v4

    - name: Cache sccache download
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.SCCACHE_FILENAME }}
        key: ${{ env.SCCACHE_FILENAME }}

    - name: Install sccache
      run: |
        set -e
        if [ ! -f "${{ env.SCCACHE_FILENAME }}" ]; then
          wget https://github.com/mozilla/sccache/releases/download/${{ env.SCCACHE_VERSION }}/${{ env.SCCACHE_FILENAME }}
        fi
        tar -xzf ${{ env.SCCACHE_FILENAME }}
        sudo mv sccache-${{ env.SCCACHE_VERSION }}-x86_64-unknown-linux-musl/sccache /usr/local/bin/
        sccache --version

    # magic to make sccache work with GitHub Actions
    # (copied from https://github.com/mozilla/sccache/blob/9fb942eec53fb67ac05dfaf73ee7ed6f87388bf2/docs/GHA.md)
    - name: Configure sccache
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Cache Rust toolset
      uses: actions/cache@v4
      with:
        path: |
          ~/.rustup
        key: rust-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/rust-toolchain.toml') }}

    - name: Cache Cargo output
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          target/
          target-coverage/
        key: cargo-test-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock', 'scripts/install_cargo-tarpaulin.sh', 'scripts/coverage.sh', 'scripts/build_fuzz.sh', '**/rust-toolchain.toml') }}

    - name: Run tests with coverage
      run: ./coverage.sh

    - name: Building fuzzers
      run: ./scripts/build_fuzz.sh

    - name: sccache stats
      run: sccache --show-adv-stats

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        file: target-coverage/lcov.info
        format: lcov
